### ISSUE TITLE
🎂 [RELEASE] Release v3.1.2 – Groups, Map, Events, Chat

### ISSUE THREAD

**Issue by Tirokk** [IT4Change/freilernen.social#1]
## 🎂 Release

Release v3.1.2 – Groups, Map, Events, Chat

### Todo

- [x] create SECRET
- [x] add SECRET and DockerHub settings to repo
- [x] create and set `SMTP_DKIM_PRIVATKEY`
  - [ ] does new multiline notation this work on the Kubernetes cluster?
- [x] set `kubeconfig.yaml`
- [x] set ocelot version and build number
