### ISSUE TITLE
🎂 [RELEASE] Release v3.1.3 – Fix Events, Header Menu Link

### ISSUE THREAD

**Issue by Tirokk** [IT4Change/freilernen.social#6]
## 🎂 Release

Release v3.1.3 – Fix Events, Header Menu Link

### Todo

- [ ] header menu links
  - [ ] change `ASP` link to `https://freilernen.de` (was `https://freilernen.com`)
  - [ ] add link to Hermanns Flohmarkt
- [x] filters are not visible
  - done by PR in main code
- [ ] search menu and search page shows no results on typing and pressing enter in the search field, see image
  - [ ] indexes may be missing in the database?
- [ ] main code:
  - [ ] configurations in `deployment\constants\.` are not used in backend by Dockerfile?
    - [ ] it's not working for `groups.ts` and `DESCRIPTION_WITHOUT_HTML_LENGTH_MIN` at the end
- [ ] rearrange branding JS files?
- [ ] add Neo4j configurtion `NEO4J_dbms_default__database` to the Kubernetes values of the Helm script
  - [ ] `DBMS_DEFAULT_DATABASE: "neo4j"`
  - [ ] add to `values.yaml.template` as well
- [ ] set new version and build number

![photo_2024-07-11 17 27 39](https://github.com/wir-social/freilernen.social/assets/25344101/cf717af6-895f-46a6-8d03-37e945a03f31)
